config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "blogs#index"
  resources :blogs do
    collection do
      get :my_blogs, to: "blogs#my_blogs", as: :my_blogs
    end

    resources :comments, except: [:index, :show, :new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_rich_text :content
  
  validates :title, uniqueness: true
  validates :title, :content, presence: true

  after_create_commit :set_publication_date

  def set_publication_date
    update_column(:publication_date, DateTime.now)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog

  validates :content, presence: true

  default_scope { order(created_at: :desc) }

  # after_create_commit  { broadcast_prepend_to [blog, :comments], partial: 'comments/comment', locals: { blog: blog, comment: self, action_controls: false }, target: "blog_#{blog.id}_comments" }
  # after_update_commit -> { broadcast_replace_to [blog, :comments], partial: 'comments/comment', locals: { blog: blog, comment: self, action_controls: false }, target: "blog_comment_#{id}"  }
  # after_destroy_commit { broadcast_remove_to [blog, :comments], target: "blog_comment_#{id}" }
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # include Error::ErrorHandler
  before_action :authenticate_user!
  before_action :set_current_user, if: :user_signed_in?

  private

    def set_current_user
      Current.user = current_user
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  @@per_page = 3
  before_action :set_blog, only: [ :show, :edit, :update, :destroy ]

  def index
    @title = "All Blogs"
    @blogs = 
      Blog
        .all
        .paginate(page: params[:page], per_page: @@per_page)
  end

  def my_blogs
    @title = "My Blogs"
    @blogs = 
      current_user
      .blogs
      .paginate(page: params[:page], per_page: @@per_page)

    render :index
  end

  def show; end

  def new
    @blog = Blog.new
  end

  def edit; end

  def create
    @blog = current_user.blogs.build(blog_params)

    if @blog.save
      redirect_to blogs_url, notice: 'Blog post is successfully created!'
    else
      render :new
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_url, notice: "Blog post is successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_url, notice: 'Blog post is successfully destroyed!'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_blog
  before_action :set_comment, only: [ :edit, :update, :destroy ]

  def edit; end

  def create
    @comment = @blog.comments.build(comment_params.merge(user_id: current_user.id))
    @comment.save
    turbo_stream
  end

  def update
    @comment.update(comment_params)
    turbo_stream
  end

  def destroy
    @comment.destroy
    turbo_stream
  end

  private

    def set_blog
      @blog = Blog.find(params[:blog_id])
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def verify_user(comment: nil)
    comment&.user.id == Current.user.id
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blogs/_blog.html.slim
.w-full.bg-white.border.border-gray-200.rounded-lg.mt-5.shadow.dark:bg-gray-800.dark:border-gray-700
  div#defaultTab.flex.flex-wrap.justify-between.text-sm.font-medium.text-center.text-gray-500.border-b.border-gray-200.rounded-t-lg.bg-gray-50.dark:border-gray-700.dark:text-gray-400.dark:bg-gray-800*{'data-controller'=>'clipboard'}
    div.me-2
      = link_to blog_path(blog), data: { "clipboard-target" => "source"} do
        div#about-tab.inline-block.p-4.rounded-ss-lg
          | Published On
          =< blog.publication_date&.strftime("%d-%B-%Y")

    div.flex.justify-between.flex-wrap
      div.me-2
        = link_to 'Copy link', "javascript:void(0);", class: 'mt-1.5 text-gray-100 text-sm rounded-2xl px-4 py-2 border-2 font-semibold inline-block', data: {"action" => "clipboard#copy"}
      - if Current.user.id == blog.user.id
        div.me-2
          = link_to 'Edit', edit_blog_path(blog), class: 'mt-1.5 text-gray-100 text-sm rounded-2xl px-4 py-2 border-2 font-semibold inline-block'
        div.me-2
          = link_to 'Delete', blog_path(blog), data: { turbo_method: :delete }, class: 'mt-1.5 text-gray-100 text-sm rounded-2xl px-4 py-2 border-2 font-semibold inline-block'

  #defaultTabContent
    #about.p-4.bg-white.rounded-lg
      = link_to blog_path(blog) do
        h2.mb-3.text-3xl.font-extrabold.tracking-tight
          =< blog.title
      p.mb-3.text-gray-500.dark:text-gray-600
        =< blog.content
      hr
      a.inline-flex.items-center.font-medium.mt-1
        | By
        =< blog.user.email

app/views/blogs/_empty_state.html.slim
- unless blogs.present?
  .bg-white.rounded-lg.shadow-lg.flex.flex-col.h-max.w-full
    .px-4.py-4.md:px-6.md:py-6
      h2.text-center.text-2xl.font-semibold.mb-4
        | You don't have any Blogs yet!
      p.text-center.mt-6
        = link_to "Add Blog", new_blog_path, class: "text-white hover:bg-cyan-700 font-semibold bg-btnEdit py-2 px-4 rounded-3xl"

app/views/blogs/_form.html.slim
= turbo_frame_tag "blog_#{blog.id}"
  = form_with model: blog, data: { turbo: false } do |form|
    = render partial: 'shared/errors', locals: { object: blog }

    .mb-4
      = form.label :title, class: "block text-sm font-bold mb-2"
      = form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "write title here"
    .mb-4
      = form.label :content, class: "block text-sm font-bold mb-2"
      = form.rich_text_area :content, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "write content here"
    .mb-6
      = form.submit "Publish", class: "mr-1 bg-sky-600 hover:bg-sky-700 font-bold py-2 px-4 rounded-3xl focus:outline-none focus:shadow-outline"
      -if blog.persisted?
        = link_to 'Cancel', blog_path(blog), class: 'mt-1.5 rounded-3xl px-4 py-2 border-2 font-semibold inline-block'

app/views/blogs/edit.html.slim
.flex.justify-between.items-center.mb-6.flex-wrap.gap-y-4
  .font-semibold.text-2xl.md:text-3xl.font-semibold
    | Edit Blog
.max-w-7xl.mx-auto.bg-white.overflow-hidden.p-4.rounded
    = render partial: 'form', locals: { blog: @blog }

app/views/blogs/index.html.slim
.flex.justify-between.items-center.mb-6.flex-wrap.gap-y-4
  .font-semibold.text-2xl.md:text-3xl.font-semibold
    = @title

= render partial: "blogs/empty_state", locals: { blogs: @blogs }
= render @blogs

.flex.items-center.justify-center.digg_pagination.my-6
  = will_paginate @blogs

app/views/blogs/new.html.slim
.flex.justify-between.items-center.mb-6.flex-wrap.gap-y-4
  .font-semibold.text-2xl.md:text-3xl.font-semibold
    | New Blog
.max-w-7xl.mx-auto.bg-white.overflow-hidden.p-4.rounded
    = render partial: 'form', locals: { blog: @blog }

app/views/blogs/show.html.slim
= turbo_stream_from @blog, :comments

.max-w-7xl.mx-auto.py-8
  .bg-white.rounded.shadow-md.mb-6
    .px-6.py-6
      = link_to blog_path(@blog) do
        h2.text-3xl.font-semibold.mb-4.text-center
          =< @blog.title
        hr
      p.text-gray-700.mb-2.mt-5
        = @blog.content
      hr
      p.text-gray-500.mt-1.text-sm.mt-1
        | Published On 
        = @blog.publication_date&.strftime("%d-%B-%Y")
    - if @blog.user_id == Current.user.id
      .px-6.pb-6.flex.justify-between
        = link_to "Edit", edit_blog_path(@blog), class: "bg-sky-600 hover:bg-sky-700 font-bold py-2 px-4 rounded-3xl focus:outline-none focus:shadow-outline py-2 px-4 rounded-3xl"
        = link_to "Destroy", blog_path(@blog), data: { turbo_method: :delete }, class: "bg-red-700 font-semibold bg-btn py-2 px-4 rounded-3xl"

  - if user_signed_in?
    = render partial: 'comments/new', locals: { blog: @blog, comment: Comment.new }

  p.text-gray-700.mb-2.mt-5
    | Comments
  div id="#{dom_id(@blog)}_comments" class="mt-4"
    - if @blog.comments.present?

      - @blog.comments.each do |comment|
        = render partial: 'comments/comment', locals: { blog: @blog, comment: comment, action_controls: comment.user.id == Current.user.id }
    - else
        p.text-gray-500.mt-1.text-sm.mt-1
          | No comments

app/views/comments/_comment.html.slim
= turbo_frame_tag "blog_comment_#{comment.id}"
  .mt-3
    .p-4.rounded-lg.shadow-md.bg-white
      span.text-sm.text-gray-700
        | By #{comment.user.email} on #{comment.created_at.strftime("%d-%B-%Y")}
      hr
      p.mt-2.text-gray-600.mb-5
        = comment.content

      - # if verify_user(comment: comment)
      - if action_controls
        .py-2
          = turbo_frame_tag "#{dom_id(comment)}"
            = link_to "Edit Comment", edit_blog_comment_path(blog, comment), class: "bg-sky-600 hover:bg-sky-700 font-bold py-2 px-4 rounded-3xl focus:outline-none focus:shadow-outline py-2 px-4 rounded-3xl"
            = link_to "Destroy", blog_comment_path(blog, comment), data: { turbo_method: :delete }, class: "ml-4 bg-red-700 font-semibold py-2 px-4 rounded-3xl"

app/views/comments/_edit.html.slim
= turbo_frame_tag "#{dom_id(comment)}" do
  = form_with(model: [blog, comment]) do |form|
    = render partial: 'shared/errors', locals: { object: comment }

    .mb-4
      = form.label :content, class: "py-3 text-sm font-bold"
      = form.text_area :content, class: "shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none", placeholder: "write comment here"

    .mb-6
      = form.submit 'Post', class: "bg-sky-600 hover:bg-sky-700 font-bold py-2 px-4 rounded-3xl focus:outline-none focus:shadow-outline p-2 rounded-3xl"

app/views/comments/_new.html.slim
= turbo_frame_tag "new_comment_form" do
  = form_with(model: [blog, comment]) do |form|
    = render partial: 'shared/errors', locals: { object: comment }

    .mb-4
      = form.label :content, class: "py-3 text-sm font-bold"
      = form.text_area :content, class: "shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none", placeholder: "write comment here"

    .mb-6
      = form.submit 'Post', class: "bg-sky-600 hover:bg-sky-700 font-bold py-2 px-4 rounded-3xl focus:outline-none focus:shadow-outline p-2 rounded-3xl"

app/views/comments/create.turbo_stream.slim
- if @comment.errors.any?
  = turbo_stream.replace "new_comment_form", partial: 'comments/new', locals: { blog: @blog, comment: @comment }
- else
  = turbo_stream.prepend "#{dom_id(@blog)}_comments", partial: 'comments/comment', locals: { blog: @blog, comment: @comment, action_controls: @comment.user.id == Current.user.id }
  = turbo_stream.replace "new_comment_form", partial: 'comments/new', locals: { blog: @blog, comment: Comment.new }
  = @comment.broadcast_prepend_to([@blog, :comments], partial: 'comments/comment', locals: { blog: @blog, comment: @comment, action_controls: @comment.user.id == Current.user.id }, target: "blog_#{@blog.id}_comments")

app/views/comments/destroy.turbo_stream.slim
= turbo_stream.remove "blog_#{@comment.id}"
= @comment.broadcast_remove_to([@blog, :comments], target: "blog_comment_#{@comment.id}")

app/views/comments/edit.html.slim
= render partial: 'comments/edit', locals: { blog: @blog, comment: @comment }

app/views/comments/update.turbo_stream.slim
- if @comment.errors.any?
  = turbo_stream.replace @comment, partial: 'comments/edit', locals: { blog: @blog, comment: @comment }
- else
  = turbo_stream.replace "blog_comment_#{@comment.id}", partial: 'comments/comment', locals: { blog: @blog, comment: @comment, action_controls: @comment.user.id == Current.user.id }
  = @comment.broadcast_replace_to([@blog, :comments], partial: 'comments/comment', locals: { blog: @blog, comment: @comment, action_controls: false }, target: "blog_comment_#{@comment.id}")

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | BlogApp
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"
  body
    = render 'shared/navbar'
    main.container.mx-auto.justify-center
      .max-w-full.md:max-w-7xl.mx-auto.py-4.md:py-8
        = yield

app/views/layouts/pdf.html.slim
doctype html
html
  head
    title
      | BlogApp
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"
  body
    main.container.mx-auto.justify-center
      .max-w-full.md:max-w-7xl.mx-auto.py-4.md:py-8
        = yield

app/views/pdfs/invoice.html.erb
<h1><%= user.email %></h1>

app/views/shared/_errors.html.slim
- if object.errors.any?
  .mb-4.text-red-500
    - object.errors.full_messages.each do |message|
      li = message

app/views/shared/_navbar.html.slim
nav.bg-white.border-gray-200.dark:bg-gray-900.dark:border-gray-700
  .max-w-screen-xl.flex.flex-wrap.items-center.justify-between.mx-auto.p-4
    a.flex.items-center.space-x-3.rtl:space-x-reverse[href="#"]
      img.h-8[src="https://flowbite.com/docs/images/logo.svg" alt="Flowbite Logo"]
      span.self-center.text-2xl.font-semibold.whitespace-nowrap.dark:text-white 
        | Blog App
    #navbar-dropdown.hidden.w-full.md:block.md:w-auto
      ul.flex.flex-col.font-medium.p-4.md:p-0.mt-4.border.border-gray-100.rounded-lg.bg-gray-50.md:space-x-8.rtl:space-x-reverse.md:flex-row.md:mt-0.md:border-0.md:bg-white.dark:bg-gray-800.md:dark:bg-gray-900.dark:border-gray-700
        - if user_signed_in?
            li
              = link_to "Add New Blog", new_blog_path, class: "block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500 dark:bg-blue-600 md:dark:bg-transparent"
            li
              = link_to "All Blogs", root_path, class: "block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500 dark:bg-blue-600 md:dark:bg-transparent"
            li
              = link_to "My Blogs", my_blogs_blogs_path, class: "block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500 dark:bg-blue-600 md:dark:bg-transparent"
            li
              = link_to 'Profile', edit_user_registration_path, class: 'block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500 dark:bg-blue-600 md:dark:bg-transparent'
            li
              = link_to 'Logout', destroy_user_session_path, class: 'block py-2 px-3 text-white bg-danger-700 rounded md:bg-transparent md:text-danger-700 md:p-0 md:dark:text-danger-500 dark:bg-danger-600 md:dark:bg-transparent'
        - else
            li
              = link_to 'Log in', new_user_session_path, class: 'block py-2 px-3 text-white bg-danger-700 rounded md:bg-transparent md:text-danger-700 md:p-0 md:dark:text-danger-500 dark:bg-danger-600 md:dark:bg-transparent'